### ISSUE TITLE
PACKAGES: official navigation rail widget released

### ISSUE THREAD

**Issue by winwisely111** [getcouragenow/packages#305]
Flutter introduced a new component in the Material library: Navigation Rail.
Design spec: https://material.io/components/navigation-rail/

https://github.com/flutter/flutter/pull/49574

**Comment by winwisely99** [comment]
Also ad Tabs for each App, because we will need this for sub navigation in each app to make it easy to navigate to separate screens of an App.

Here is a example screenshot:
https://storage.googleapis.com/spec-host/mio-staging%2Fmio-components%2F1584058305895%2Fassets%2F1Dzg8RXsMLZ3MirgO2v-WKFkRSHpfGUD4%2Frail-behavior-nav-tabs.png

This does it nicely automatically using between Cupertino and Material Tabs.
https://github.com/pd4d10/git-touch

Uses Cases for using this UI Pattern:
- A standard one is to create Tabs like in a browser so you can have many tabs open at the same time, and close them when not needed. It is exactly what everyone does in a Web Browsr to work on many things at the same time. In our case its per app though which is not so useful.

---
