### ISSUE TITLE
PACKAGES: mod-main cant route to Login up in maintemplate

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/packages#358]
Login is in maintemplate:
https://github.com/getcouragenow/packages/blob/master/maintemplate/client/lib/core/routing/router.dart#L3

mod-main is trying to route to a route up in mainTemplate called "/login":

https://github.com/getcouragenow/packages/blob/master/mod-main/client/lib/modules/orgs/views/org_detail_view.dart#L155

// TODO: Require help on this one, couldn't figure out why the paths aren't recognised...
// Modular.to.pushNamed(Modular.get<Paths>().login);
// Navigator.of(context).pushNamed("/login");

Both throws:
Exception was thrown: Could not find a generator for route RouteSettings("/login", null) in the _WidgetsAppState.

Which makes sense :)

Options ?

Move all the mod-main code into maintemplate.
I really prefer not as i want to be able to swap out mod-main with other mod-main-customerX, mod-main-customerY later. 

Another Option:
Fire an event to mainTemplate with a string of the Route we want.
then maintemplate does the:
Modular.to.pushNamed("route asked for from mod-main);
Back button might not work....

This brings up an Architectural Issue that we are going to hit.
HOW to navigate across Modules ?
Like Layer 2 Kan Ban, will navigate to mod-X.
Back button will work of course, but NOT actual Button clicks where we want to specifically navigate we want to pick a Module to route to.

**Comment by arthurdenner** [comment]
I've noticed that the `/login` (`Paths.login`) route is not registered in the AppModule. It's declared in `LoginModule` but this module is not registered anywhere. I didn't run your project locally, but here is my suggestion:

- Add `Router(Paths.login, module: LoginModule())` in the `routers` of `app_module.dart`;
- Use `Router('/', child: (context, args) => LoginView())` in `login_module.dart`.

I believe it may work with this because `/login` will be registered as a module in the AppModule and its main route will be `/`.

**Comment by joe-getcouragenow** [comment]
also brow, i create this sample, i guess this will help u. https://github.com/Bwolfs2/how_to_do/tree/master/hwd_modules

in this example I used Modules instead of Packages, because that way the Module could be used even in Native projects

**Comment by joe-getcouragenow** [comment]
DOD:
All the buttons in main-mod working back to Signin

**Comment by joe-getcouragenow** [comment]
you missed the last route:
https://maintemplate.ci.getcouragenow.org/#/enrollement/supportRoles/orgs/1

NEXT button to go to Signup
