### ISSUE TITLE
PACKAGES: Dashboard behavious wrong

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/packages#455]
https://maintemplate.ci.getcouragenow.org/#/dashboard/orgs

All on Web Desktop..

1. ULR values wrong. Use integers or UUID like the DB will be

2. On load right pane should be like main and said "no content loaded"

3. Left pane flashes !!

4. Printing not working
- Right pane not shown
- Vertical page of the page not shown

- Might want to consider only printing the right Detail pane with a dedicated print button.

5. Share button is wrong path.

6. Row per page not working.
- changing it but the choices in a weird place.

7. Mobile
- Pagination tools not showing.

**Comment by winwisely111** [comment]
1- For testing purpose, the value passed is organization name to keep it simple nd not make mock data class, its intentional, with real data, organization id will be passed only....

2- on load, there is no organisation selected yet, as the url suggests, dashboard/orgs/,
Thats y right pane shows no item selected. 

3- will check

4- okiee can look into it

5- yess it's wrong path, we don't need that share button now bcz omni box now shows right url, so either ways thats going to be removed..

6- about rows per page, that functionality is not implemented, but its there to be implemented with real data, nd thats bcz not sure if the call will fetch all orgs data nd save in memory, or when the per page rows is changed, then only more orgs data will be fetched from server, choice needs to be made, so once real data is pumped this functionality can be implemented with right choice

**Comment by joe-getcouragenow** [comment]
I think you misunderstood most of this.

Look just leave it for now.

**Comment by winwisely99** [comment]
gen data for

actiontime (datetime), actionlocation (later), minpioneer(int)

**Comment by winwisely99** [comment]
campaingname is a sequence number going up after the name , so on mobile we can see

**Comment by winwisely104** [comment]
- pagination is not possible with the currently used package for mobile
- filters functionality fix missing
- printer stuff not touched
all other points are done

**Comment by winwisely104** [comment]
sorting on mobile is working, easy to activate another category.

On the bottom sheet there is bug -> the radio button has to be clicked twice.

**Comment by winwisely104** [comment]
Remaining: The bug on the bottom sheet (radio button has to be clicked twice). Should we close this an open a new issue for it? @joe-getcouragenow

**Comment by winwisely99** [comment]
Open an issue on their git please.
I also saw that bug.
