### ISSUE TITLE
PACKAGES: Lang and Rail overflows for certain languages

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/packages#517]
https://youtu.be/rAC4eIOtfIw

Reduce the padding and / or increase the width of the container..

This is a common problem with i18n.

---

**Comment by winwisely104** [comment]
![Screenshot 2020-05-04 at 10 33 08](https://user-images.githubusercontent.com/61538094/80948645-d5fdbf00-8df2-11ea-9fe6-58ba3056d138.png)
 also fixed for german language where settings is: "Einstellungen"

**Comment by joe-getcouragenow** [comment]
@winwisely104 

Desktop and Tablet
- offset breakpoint between left rail and right master view, so that rail is always 30 dp units off from the widest text.

Mobile
- let it flow.

**Comment by winwisely104** [comment]
Nav rail has now a flexible width, depending on the length of the translations.

Added GetCourageMasterDetail for Writer (wasn't there yet, url were not working, now they are!)

Regarding the master page i reduced only the width. It's not flexible depending on the content right now, because we have one master view with a search bar, the other without. If we abstract this out we can make it flexible - but a fixed small width is more consistent for a user... (my opinion)
