### ISSUE TITLE
Multiple widgets used the same GlobalKey.

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/packages#518]
Also i got this in the logs constantly:
flutter: Another exception was thrown: Multiple widgets used the same GlobalKey.
It does not say where :)

We should sort this out early before it bits us.

anyone know how to turn on logging with stack trace so we can see where its coming from ?

maybe we should put in a stack trace helper that can be turned on and off via settings ?

also this: https://github.com/flutter/sentry
Sentry is easy to self run on our servers.

**Comment by winwisely104** [comment]
Sentry is a good option to track stacktraces. In this specific case it wouldn't have helped since the stacktrace on duplicate key errors isn't with much informations. I could track it down and the problem relied on a mixture between using flutter modular and responsive widgets using in the MaterialApp builder method, where the navigator is not yet accessible. I fixed it by using a UniqueKey for our Rail so when resizing the Rail it gets every time a new key, that may have (small) effects on the resizing performance. With new keys the view will not be recycled. It's not the finest solution but was the fastest. Since people are not resizing windows all day, i think it's good until we encounter performance issues. ( I tested in debug mode which is much slower then production and haven't had ANY issues on performance, while resizing)
