### ISSUE TITLE
PACKAGES: Mod-main : uploading functionality

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#529]
You played with tusd ? 

The issue is to get uploads working from the Flutter Client and Golang CLI

We have data flowing using grpc and grpc-web. Can and should be use it for file upload ?
The alternative is S3 via Minio.

We need offline first story, which means that if the connection breaks it will resume the upload.

We want to avoid all native dependencies in the flutter client, so its possible that maybe we suck the file(s) to be uploaded first into the Flutter directory, and then upload from there, because then resume has it there and can carry on when Flutter starts up again.

That requires chunking and envoy and golang and flutter knowledge.

Do as part of mod-main and mod-account
Mod-account requires profile image upload.
Mod-main requires org profile image upload.

DOD:
CLI from golang work for each mod.

GUI from flutter work for each mod

Core that is shared is abstracted out to sys-core as per normal.

**Comment by joe-getcouragenow** [comment]
Has anyone taken  this ????

**Comment by joe-getcouragenow** [comment]
Note that the protobufs will also have a image name and image path

SO then a user can upload data with an image.

The image name needs to be assigned a UUID on the client first then, because the data in the protobuf will transact to the backend before the image has arrived.
The path is not know until its transacted so the what has to happen is that the data in the protobuf is sent first and a Path allocated for it ? Not sure.. Lets see how it pans out
