### ISSUE TITLE
PACKAGE: DB based on Bitcask  ( Research )

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#74]
https://github.com/prologic/bitcask
- Redis implementation (kv) 
- genji integration ( not yet, but possible) for SQL
- GRPC wrapper.
- op 
  - docker ( k8 yaml )
  -  rasp pi ( baremetal)

https://github.com/prologic/bitraft
- redcon : redis API and raft abstractions. 
- THE HA.
  - single possible of course
- same globally ( no shards)
  - Multi DC: Need regioning. 
  - Currently
     - 1 per DC ( 3 DC's). So scale per DC is issue.
     -  3 per DC ( RAFT them).  then higher level multi DC. 
         -Use https://github.com/lni/dragonboat ?
              - peeble too.

Sensible gameplan we think.
--------------------------
0. Use bitcask
 - today can have 1 per DC with 3 DC's
 - self recovers :)
 - ops layer not yet.
3. BitCask then uses Dragonboat ( which under the hood uses Pebble to distribute the log, etc ) 
 - Now have multi dbs per DC and multi DC's.
2. BitSQL using BitCask. Genji API implementation that see BitCask.
- Now have SQL API.

Can also use bitcask instead of pebble.
https://github.com/lni/dragonboat/blob/master/docs/storage.md#use-custom-storage-solution

**Comment by prologic** [comment]
> ops layer not yet.

There exist some "ops" tooling already for Bitcaks itself (_the embedded KV eigne_); namely:

- `bitcask import` -- Import a DB from an exporte.
- `bitcask export` -- Export a DB (_exports to JSON stream_)
- `bitcask recover` -- Recovers a corrupt database and reconstructs indicies.
- `bitcask stats` -- Display DB stats

What is missing in order to complete "ops layer"?

**Comment by winwisely99** [comment]
For ops o was thinking about when a cluster is setup and the ops person needs to run a system.
Stuff like adding a new nofe to a cluster and removing one.
